@startuml
allowmixing
skinparam linetype ortho
rectangle additionalElements
rectangle value
rectangle properties
rectangle "additionalElements" as a2
rectangle processes

object additionalElement
additionalElement : name
additionalElement : dataType
additionalElement : format

additionalElements --|{ additionalElement

additionalElement --o| value
additionalElement --o| properties
additionalElement --o| a2
additionalElement --o| processes
@enduml
