@startuml
allowmixing
skinparam linetype ortho

rectangle period

rectangle {
object startDate
object endDate
}

startDate : value = 20000101
endDate : value = 20101231

period --|| startDate
period --|| endDate
@enduml
