@startuml
allowmixing
skinparam linetype ortho

rectangle "reference" as p1
rectangle "description" as c1
rectangle "additionalElements" as c2
rectangle "processes" as c3
object "context" as e
p1 --o| e
e --o| c1
e --o| c2
e --o| c3
@enduml