@startuml
allowmixing
skinparam linetype ortho

rectangle "dataObjects" as p1
rectangle "description" as c1
rectangle "properties" as c2
rectangle "dataObjects" as c3
rectangle "processes" as c4
object "dataObject" as e
e : name
p1 --|{ e
e --o| c1
e --o| c2
e --o| c3
e --o| c4
@enduml