@startuml
allowmixing
skinparam linetype ortho

rectangle "dataset" as p1
rectangle "dataObject" as p2
rectangle "description" as c1
rectangle "dataObject" as c2
rectangle "processes" as c3
object "dataObjects" as e
p1 --o| e
p2 --o| e
e --o| c1
e --|{ c2
e --o| c3
@enduml