@startuml
allowmixing
skinparam linetype ortho

rectangle "properties" as p1
rectangle "value" as c1
rectangle "properties" as c2
object "property" as e
e : name
e : dataType
e : format
p1 --|{ e
e --o| c1
e --o| c2
@enduml