@startuml
allowmixing
skinparam linetype ortho

rectangle "recordDefinitionReferences" as p1
rectangle "fieldDefinitionReferences" as c1
object "recordDefinitionReference" as e
e : name
p1 --|{ e
e --o| c1
@enduml