@startuml
allowmixing
skinparam linetype ortho

rectangle "dataset" as p1
rectangle "context" as c1
rectangle "content" as c2
object "reference" as e
e : name
p1 --o| e
e --o| c1
e --o| c2
@enduml