@startuml
left to right direction
rectangle flatFile
rectangle recordDefinition
rectangle flatFileDefinition
rectangle fieldDefinition

flatFile -- flatFileDefinition
flatFileDefinition -- recordDefinition
recordDefinition -- fieldDefinition
@enduml
