@startuml
skinparam linetype ortho

skinparam package<<Layout>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}

package files <<Layout>> {
rectangle flatFiles
rectangle flatFile
}

package definitions <<Layout>> {
rectangle flatFileDefinitions
rectangle flatFileDefinition
rectangle recordDefinitions
rectangle recordDefinition
rectangle fieldDefinitions
rectangle fieldDefinition
}

package types <<Layout>> {
rectangle structureTypes
rectangle flatFileType
rectangle recordType
rectangle fieldType
}


flatFiles --- flatFile
flatFiles -- flatFileDefinitions
flatFile - flatFileDefinition

flatFileDefinitions -- flatFileDefinition
flatFileDefinition -- recordDefinitions
recordDefinitions -- recordDefinition
recordDefinition -- fieldDefinitions
fieldDefinitions -- fieldDefinition

flatFileDefinition - flatFileType
recordDefinition - recordType
fieldDefinition - fieldType

structureTypes -- flatFileType 
flatFileType --[hidden]- recordType
recordType--[hidden]- fieldType
structureTypes -- recordType
structureTypes -- fieldType

flatFiles -- structureTypes
@enduml
